ejbca:
    # Values required to access the EJBCA:
    cahost:
    clientP12ArchiveFilepath:
    clientP12ArchivePassword:
    managementCA:

    # Endpoint:
    endpoint: /certificate/pkcs10enroll
    # Values required by the endpoint "/pkcs10enroll":
    certificateProfileName:
    endEntityProfileName:
    username:
    password:
    includeChain: true

    countries:
        - country: CZ
          certificateAuthorityName: PID Issuer CA - CZ 02
        - country: EE
          certificateAuthorityName: PID Issuer CA - EE 02
        - country: EU
          certificateAuthorityName: PID Issuer CA - EU 02
        - country: LU
          certificateAuthorityName: PID Issuer CA - LU 02
        - country: NL
          certificateAuthorityName: PID Issuer CA - NL 02
        - country: PT
          certificateAuthorityName: PID Issuer CA - PT 02
        - country: default
          certificateAuthorityName: PID Issuer CA - UT 02
